// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfwsybC8YpoqKviOKKE1oU5bPe5V7pHMY',
    appId: '1:787745307493:web:5fbd11dda3192c53f83f8c',
    messagingSenderId: '787745307493',
    projectId: 'sokar-d14c2',
    authDomain: 'sokar-d14c2.firebaseapp.com',
    storageBucket: 'sokar-d14c2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx7CBhUregoKvg1k1pec0XSpqnpJf8Hq4',
    appId: '1:787745307493:android:b4a748acae7a6e6cf83f8c',
    messagingSenderId: '787745307493',
    projectId: 'sokar-d14c2',
    storageBucket: 'sokar-d14c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2tmiO3WE8Q_l1qFBYWdMdXQscofqovMw',
    appId: '1:787745307493:ios:85ba77571e9ea8acf83f8c',
    messagingSenderId: '787745307493',
    projectId: 'sokar-d14c2',
    storageBucket: 'sokar-d14c2.firebasestorage.app',
    iosBundleId: 'com.example.flutterSokar',
  );
}
